apiVersion: v1
kind: Service
metadata:
  name: wso2-is-identity-server-http
  namespace: wso2
spec:
  selector:
    app.kubernetes.io/instance: wso2-is
    app.kubernetes.io/name: identity-server
  ports:
    - name: servlet-http
      port: 9763
      targetPort: 9763
      protocol: TCP
