nameOverride: "user-service"
fullnameOverride: "user-service"
replicaCount: 2

image:
  repository: "<registry>/<namespace>/super-admin-service"
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 8000
command: []
args: []

service:
  enabled: true
  type: ClusterIP
  port: 80

config:
  DATABASE_URL: "postgresql://postgres:password@postgres-postgresql.database.svc.cluster.local:5432/ceylonstaydb"

secrets: {}

resources: {}
