nameOverride: "admin-service"
fullnameOverride: "admin-service"
replicaCount: 2

image:
  repository: "kushanrandika/user-service:v1.0.0"
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 8000
command: []
args: []

service:
  enabled: true
  type: ClusterIP
  port: 80

config:
  DATABASE_URL: "postgresql://postgres:password@postgres-postgresql.database.svc.cluster.local:5432/ads"

secrets: {}

resources: {}
