nameOverride: "ai-service"
fullnameOverride: "ai-service"
replicaCount: 1

image:
  repository: "<registry>/<namespace>/ai-service"
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 0
command:
  - "python"
args:
  - "app/worker.py"

service:
  enabled: false
  type: ClusterIP
  port: 80

config:
  DB_DSN: "dbname=ads user=postgres password=password host=postgres-postgresql.database.svc.cluster.local port=5432"
  RABBITMQ_HOST: "rabbitmq.database.svc.cluster.local"
  MINIO_ENDPOINT: "minio.database.svc.cluster.local:9000"

secrets:
  MINIO_ACCESS: "minioadmin"
  MINIO_SECRET: "minioadmin"

resources: {}
