apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "svc.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "svc.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "svc.fullname" . }}
      annotations:
        sidecar.istio.io/inject: "true"
        {{- if .Values.rabbitmqPatch.enabled }}
        checksum/rabbitmq-patch: {{ include (print $.Template.BasePath "/rabbitmq-patch-configmap.yaml") . | sha256sum }}
        {{- end }}
    spec:
      containers:
        - name: {{ include "svc.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command:
{{ toYaml .Values.command | indent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args:
{{ toYaml .Values.args | indent 12 }}
          {{- end }}
          {{- if gt (int .Values.containerPort) 0 }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          {{- end }}
          {{- if .Values.rabbitmqPatch.enabled }}
          volumeMounts:
            - name: rabbitmq-py-override
              mountPath: /app/app/rabbitmq.py
              subPath: rabbitmq.py
          {{- end }}
          {{- if or .Values.config .Values.secrets }}
          envFrom:
            {{- if .Values.config }}
            - configMapRef:
                name: {{ include "svc.fullname" . }}-config
            {{- end }}
            {{- if .Values.secrets }}
            - secretRef:
                name: {{ include "svc.fullname" . }}-secret
            {{- end }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- if .Values.rabbitmqPatch.enabled }}
      volumes:
        - name: rabbitmq-py-override
          configMap:
            name: {{ include "svc.fullname" . }}-rabbitmq-patch
      {{- end }}
