nameOverride: "notification-service"
fullnameOverride: "notification-service"
replicaCount: 2

image:
  repository: "<registry>/<namespace>/notification-service"
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 8000
command: []
args: []

service:
  enabled: true
  type: ClusterIP
  port: 80

config:
  DATABASE_URL: "postgresql://postgres:password@postgres-postgresql.database.svc.cluster.local:5432/ads"
  RABBITMQ_HOST: "rabbitmq.database.svc.cluster.local"
  RABBITMQ_PORT: "5672"

secrets: {}

resources: {}
