nameOverride: "ads-service"
fullnameOverride: "ads-service"
replicaCount: 2

image:
  repository: "kushanrandika/ads-service"
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

containerPort: 8000
command: []
args: []

service:
  enabled: true
  type: NodePort
  port: 80
  nodePort: 30134

ingress:
  enabled: true
  host: ads-api.tail97d15d.ts.net
  path: /

config:
  DATABASE_URL: "postgresql://postgres:postgres123@postgres-postgresql.database.svc.cluster.local:5432/ceylonstaydb"
  RABBITMQ_HOST: "rabbitmq.database.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_URL: "amqp://admin:admin123@rabbitmq.database.svc.cluster.local:5672/%2F"
  AMQP_URL: "amqp://admin:admin123@rabbitmq.database.svc.cluster.local:5672/%2F"
  MINIO_ENDPOINT: "minio.database.svc.cluster.local:9000"
  REDIS_HOST: "redis-master.database.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  RABBITMQ_USER: "admin"
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_DEFAULT_USER: "admin"

secrets:
  MINIO_ACCESS: "minioadmin"
  MINIO_SECRET: "minioadmin123"
  REDIS_PASSWORD: "redis123"
  RABBITMQ_PASS: "admin123"
  RABBITMQ_PASSWORD: "admin123"
  RABBITMQ_DEFAULT_PASS: "admin123"

resources: {}

rabbitmqPatch:
  enabled: true
