nameOverride: "super-admin-service"
fullnameOverride: "super-admin-service"
replicaCount: 2

image:
  repository: "kushanrandika/super-admin-service"
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

containerPort: 8000
command: []
args: []

service:
  enabled: true
  type: ClusterIP
  port: 80

config:
  DATABASE_URL: "postgresql://postgres:postgres123@postgres-postgresql.database.svc.cluster.local:5432/ceylonstaydb"

secrets: {}

resources: {}
